version: '3'
services:
#mysql配置
    mysql:
        environment:
#root账号的密码
            MYSQL_ROOT_PASSWORD: "123456"
        image: "mysql:latest" 
        container_name: mysql_docker_compose
        restart: always
        ##映射挂载
        volumes:
#数据目录，要确保先创建好
            # - "/data/mysql:/var/lib/mysql"
            ##初始化的脚本，初始化我们存放的init.sql文件
            - "./mysql:/docker-entrypoint-initdb.d/"
        ports:
            - "3307:3306"
        command: "--default-authentication-plugin=mysql_native_password "
    ##redis配置
    redis:
      image: redis:latest
      container_name: redis
      command: redis-server --appendonly yes --requirepass "123456"
      ports:
        - "6379:6379"
    #   volumes:
#数据目录，要确保先创建好
        # - /data/redis:/data

